version: 2.0.0
last_updated: '2026-03-29T18:05:14.949226'
updated_by: dashboard-ui
environment_name: PERF
lab_environment: T5A
release_code: N
application_key: csi-gateway
application_display_name: CSI Common Services Gateway
api_variant: core
applications:
- app_name: CSI Common Services Gateway
  app_description: CSI Common Services Gateway (REST + SOAP)
  tags:
  - middleware
  - csi
  - critical
  - lab-t3a
  config_fields:
  - field_name: TLG_ENDPOINT
    expected_perf_value: https://tlg-perf.internal.att.com:9443
    inspection_tool: azure_cli
    description: Amdocs TLG backend endpoint
    known_qc_values:
    - https://tlg-qc3.internal.att.com:9443
    remediation_level: suggest_fix
    remediation_command: null
  - field_name: BSSE_ENDPOINT
    expected_perf_value: https://bsse-perf.internal.att.com:9443
    inspection_tool: azure_cli
    description: Amdocs BSSe billing endpoint
    known_qc_values:
    - https://bsse-qc3.internal.att.com:9443
    remediation_level: suggest_fix
    remediation_command: null
  - field_name: OMS_ENDPOINT
    expected_perf_value: https://oms-perf.internal.att.com:8443
    inspection_tool: azure_cli
    description: Amdocs OMS order management
    known_qc_values:
    - https://oms-qc3.internal.att.com:8443
    remediation_level: suggest_fix
    remediation_command: null
  - field_name: CAS_ENDPOINT
    expected_perf_value: https://cas-perf.internal.att.com:8443
    inspection_tool: azure_cli
    description: CAS/iCAS payment service
    known_qc_values:
    - https://cas-qc3.internal.att.com:8443
    remediation_level: suggest_fix
    remediation_command: null
  - field_name: BASE_ENDPOINT_URL
    expected_perf_value: https://csi-perf.att.com
    inspection_tool: http_probe
    description: Primary endpoint URL for this application in PERF
    known_qc_values: []
    remediation_level: suggest_fix
    remediation_command: null
