import { useState, useEffect, useRef, useCallback, useMemo } from "react";
const C={white:"#ffffff",bg:"#f5f7fa",bgCard:"#ffffff",bgMuted:"#f0f3f7",bgHover:"#e8f4fc",border:"#e0e6ed",borderLight:"#eef1f5",attBlue:"#00A8E0",attBlueDark:"#0077a8",attBlueLight:"#e5f6fc",attBlueFaint:"#f0f9fd",textPrimary:"#1a1a2e",textSecondary:"#5a6578",textMuted:"#8c96a6",success:"#0faa6c",successBg:"#edfbf4",successBorder:"#b8ecd4",warning:"#e5920a",warningBg:"#fef7ea",warningBorder:"#f5dca3",error:"#dc3545",errorBg:"#fef0f1",errorBorder:"#f5c1c6",purple:"#6f42c1",purpleBg:"#f3effa",purpleBorder:"#d4c5f0",fontSans:"'Nunito','Omnes',system-ui,sans-serif",fontMono:"'IBM Plex Mono','Menlo',monospace"};
const PHASES=[{id:"story_analysis",label:"Story Analysis",num:1},{id:"test_planning",label:"Test Planning",num:2},{id:"env_triage",label:"Env Triage",num:3},{id:"script_data",label:"Scripts & Data",num:4},{id:"execution",label:"Execution",num:5},{id:"reporting",label:"Reporting",num:6},{id:"postmortem",label:"Postmortem",num:7}];
const PHASE_DESCS={story_analysis:"Extract test cases from Jira stories + RAG",test_planning:"Build workload models, scenarios, SLAs",env_triage:"Validate PERF configs, establish golden baseline",script_data:"Generate VuGen/JMeter scripts, provision data",execution:"Run peak/break/stability tests with live monitoring",reporting:"Analyze results, publish Word/SharePoint",postmortem:"Archive lessons to Snowflake + RAG"};
const STATUS={pending:{color:C.textMuted,bg:C.bgMuted,border:C.border,label:"Pending",dot:false},running:{color:C.attBlue,bg:C.attBlueLight,border:C.attBlue+"50",label:"Running",dot:true},awaiting_approval:{color:C.purple,bg:C.purpleBg,border:C.purpleBorder,label:"Awaiting",dot:true},completed:{color:C.success,bg:C.successBg,border:C.successBorder,label:"Complete",dot:false}};
const APPS=[{id:"opus",name:"OPUS",desc:"Legacy Retail",tier:"Frontend",protocol:"Web HTTP/HTML",icon:"O"},{id:"csi",name:"CSI",desc:"Common Services GW",tier:"Middleware",protocol:"REST+SOAP",icon:"C"},{id:"gddn",name:"GDDN",desc:"Data Transform/MQ",tier:"Middleware",protocol:"Solace MQ",icon:"G"},{id:"cas",name:"CAS/iCAS",desc:"Credit & Payments",tier:"Middleware",protocol:"REST/JSON",icon:"$"},{id:"tlg",name:"TLG (Amdocs)",desc:"Customer SoR",tier:"Backend",protocol:"REST/JSON",icon:"T"},{id:"other",name:"Other",desc:"Custom Application",tier:"Other",protocol:"Various",icon:"+"}];
const AR="→",DA="—",BU="•",EL="…",UP="↑";

// Past test run history for the landing page table
const PAST_RUNS=[
  {id:"run-20260315-a",date:"2026-03-15",sprint:"Sprint 26.2",stories:["TELECOM-4488","TELECOM-4489"],apps:["OPUS","CSI","TLG"],phase:7,status:"completed",verdict:"GO",duration:"4h 12m"},
  {id:"run-20260308-b",date:"2026-03-08",sprint:"Sprint 26.2",stories:["TELECOM-4472"],apps:["OPUS","CSI","CAS/iCAS"],phase:7,status:"completed",verdict:"CONDITIONAL",duration:"5h 38m"},
  {id:"run-20260301-c",date:"2026-03-01",sprint:"Sprint 26.1",stories:["TELECOM-4451","TELECOM-4452","TELECOM-4453"],apps:["OPUS","CSI","TLG","CAS/iCAS"],phase:7,status:"completed",verdict:"NO-GO",duration:"6h 55m"},
  {id:"run-20260222-d",date:"2026-02-22",sprint:"Sprint 26.1",stories:["TELECOM-4430"],apps:["GDDN","CSI","TLG"],phase:5,status:"failed",verdict:DA,duration:"3h 10m"},
  {id:"run-20260215-e",date:"2026-02-15",sprint:"Sprint 26.0",stories:["TELECOM-4411","TELECOM-4412"],apps:["OPUS","CSI","TLG","BSSe"],phase:7,status:"completed",verdict:"GO",duration:"3h 48m"},
  {id:"run-20260208-f",date:"2026-02-08",sprint:"Sprint 26.0",stories:["TELECOM-4398"],apps:["OPUS","CSI"],phase:7,status:"completed",verdict:"GO",duration:"2h 22m"},
  {id:"run-20260131-g",date:"2026-01-31",sprint:"Sprint 25.4",stories:["TELECOM-4380","TELECOM-4381"],apps:["CSI","CAS/iCAS","TLG"],phase:7,status:"completed",verdict:"CONDITIONAL",duration:"5h 05m"},
  {id:"run-20260124-h",date:"2026-01-24",sprint:"Sprint 25.4",stories:["TELECOM-4365"],apps:["OPUS","CSI","TLG"],phase:3,status:"failed",verdict:DA,duration:"1h 15m"},
];

const AGENT_PROMPTS={
story_analysis:{role:"StoryAnalyzerAgent (GPT-4o, 4096 tok)",system:"You are a senior performance test engineer at AT&T.\n\nEnvironment:\n- Frontend: OPUS (HTTP/HTML), Salesforce/Mulesoft (REST), IDP (mobile REST)\n- Middleware: CSI (REST+SOAP), GDDN (Solace MQ), CAS/iCAS (payments)\n- Backend: TLG/Amdocs (SoR), BSSe (billing), OMS (orders)\n- Periphery: Customer/Order/Identity Graphs, Cassandra, Oracle, LDAP\n\nFor each Jira story:\n1. Fetch story details via fetch_jira_story\n2. Search enterprise knowledge (RAG) using context IDs\n3. Search past performance incidents\n4. Get Snowflake historical baselines\n5. Discover Dynatrace services\n\nProduce TestCase objects: transaction flows, protocol, SLA targets (p90/p95/err%), risk levels, recommended harness, dependencies, data requirements.\n\nHarness Rules:\n- OPUS HTTP/HTML "+AR+" LoadRunner (VuGen C)\n- REST/SOAP "+AR+" JMeter (.jmx)\n- Solace MQ "+AR+" JMeter Solace plugin",input:"Analyze stories: TELECOM-4521, TELECOM-4522\nSprint: 26.3\n\nContext IDs provided for RAG. Selected applications define scope. Fetch details, search RAG, check baselines, discover topology, identify all transaction flows."},
test_planning:{role:"TestPlanGeneratorAgent (GPT-4o, 8192 tok)",system:"Create comprehensive test plan.\n\n1. Workload Model: mix summing to 100%, TPS from prod metrics\n2. Scenarios: LOAD (always), STRESS (breakpoint >5% err), ENDURANCE (if async/MQ), SPIKE (if AKS)\n3. Env Spec: AKS namespaces, DB connections, MQ queues\n4. Data Prep: bulk data per system\n5. Monitoring: Dynatrace zones, Prometheus, ELK patterns\n6. Entry/Exit Criteria: quantified thresholds\n7. Risk Register\n\nTelecom: Stepped ramp (10-20 users/step). Billing 200-500 TPS. Plan changes 20-50 TPS. Amdocs pool risks.",input:"Create plan from 6 test cases, 12 SLAs, risk profiles. Read app configs. Query Dynatrace 7-day metrics. Get Snowflake baselines. HITL context injected below."},
env_triage:{role:"EnvConfigAgent (GPT-4o-mini, 4096 tok)",system:"Validate PERF environment.\n\nCRITICAL: All configs MUST point to PERF, NOT QC.\nFlag: qc2, qc3, QC3QM, qc-vpn, qc-scan\n\nSteps:\n1. Read perf_environment_reference.yaml\n2. Check AKS deployments, App Gateway, endpoints\n3. Compare actual vs expected PERF values\n4. Flag QC pointers as CRITICAL\n5. If ALL pass "+AR+" save golden config for drift monitoring\n\nRemediation: ALERT_ONLY "+AR+" SUGGEST_FIX "+AR+" AUTO_REMEDIATE (with approval)",input:"Validate PERF for all systems in scope. Check AKS, App Gateway, endpoints, DB connections, MQ config. Flag QC pointers. Establish golden config if all pass."},
script_data:{role:"ScriptGeneratorAgent (GPT-4o, 8192 tok)",system:"Generate scripts and provision data.\n\nVuGen: C code with web_url(), web_submit_data(), lr_start/end_transaction, web_reg_save_param correlation, lr_eval_string parameterization.\n\nJMeter: .jmx with ThreadGroup, HTTPSamplerProxy, CSV Data Set Config. REST: JSON. SOAP: envelope. Solace: JMS persistent.\n\nData: SQL (Oracle/Cassandra), API (TLG/SF), Tools (Amdocs). Check existence before creating.",input:"Generate scripts for all test cases. VuGen for OPUS, JMeter for REST/SOAP/Solace. Validate syntax + dry-run. Provision 50K customers, 100K orders, 200K billing, 5K Solace msgs."},
execution:{role:"ExecutionOrchestratorAgent (GPT-4o, 8192 tok)",system:"Execute tests:\n1. Pre-flight: verify golden config\n2. LOAD: target TPS, 30 min, verify SLAs\n3. STRESS: ramp, find breakpoint (>5% err)\n4. ENDURANCE: sustain peak 1-4hr\n5. SPIKE: 3x burst, AKS auto-scale\n\nPeak: max TPS with p90 SLA, err <1%, CPU <85%\nBreak: err >5% OR timeout >10%\n\nMonitor: Dynatrace, Prometheus, ELK.\nRouting: AKS"+AR+"Platform | Amdocs"+AR+"DBA | DB"+AR+"DBA | MQ"+AR+"Middleware",input:"Execute all scenarios. Pre-flight config check. LOAD, STRESS, ENDURANCE, SPIKE in sequence. Monitor throughout. Log anomalies. Create Jira defects."},
reporting:{role:"ResultsAnalyzerAgent (GPT-4o, 8192 tok)",system:"Analyze and report.\n\nSLA compliance per-txn. Baseline comparison from Snowflake. Defect severity: BLOCKER/CRITICAL/MAJOR/MINOR.\n\nReport: Exec Summary, Scope, SLA Compliance, Peak/Break/Stability, Anomalies, Defects, Baselines, Recommendations, Go/No-Go.\n\nDeliver: Word report, SharePoint, Snowflake, Jira defects.",input:"Analyze Phase 5 results. Compare SLAs and baselines. Generate Word report. Upload SharePoint. Archive Snowflake. Create defects. Go/no-go recommendation."},
postmortem:{role:"PostmortemAgent (GPT-4o, 8192 tok)",system:"Postmortem analysis.\n\n1. Review all phases for issues\n2. Categorize: environment, data, tooling, process, technical\n3. Calculate time lost\n4. Synthesize lessons: Title, Context, Recommendation, Tags\n5. Archive "+AR+" Snowflake\n6. Index "+AR+" RAG (Azure AI Search)\n\nFeedback: Lessons retrieved by future Phase 1 & 2 via RAG.",input:"Review 6 phases. Catalog issues. Calculate time lost. Synthesize lessons. Archive Snowflake. Index RAG for future runs."}
};
const PHASE_SIMS={
story_analysis:{duration:3500,logs:[{delay:0,lv:"INFO",m:"Phase 1 starting: Story Analysis"},{delay:300,lv:"TOOL",m:AR+" search_enterprise_knowledge(context IDs)"},{delay:600,lv:"INFO",m:"RAG: 14 docs from context IDs"},{delay:900,lv:"TOOL",m:AR+" fetch_jira_story(TELECOM-4521)"},{delay:1200,lv:"TOOL",m:AR+" fetch_jira_story(TELECOM-4522)"},{delay:1600,lv:"TOOL",m:AR+" search_past_incidents('TLG')"},{delay:2000,lv:"TOOL",m:AR+" get_performance_baselines()"},{delay:2400,lv:"TOOL",m:AR+" discover_services('perf-testing')"},{delay:2900,lv:"LLM",m:"GPT-4o "+AR+" 6 test cases (4096 tok)"},{delay:3400,lv:"INFO",m:"Phase 1 done "+DA+" 6 cases, 12 SLAs, 87%"}],result:{duration_seconds:45.2,summary:"Analyzed 2 stories "+AR+" 6 test cases\n"+BU+" 12 SLA targets (p90/p95)\n"+BU+" 2 HIGH risk (TLG, Solace MQ)\n"+BU+" 4 MEDIUM risk (billing)\n"+BU+" 87% confidence\n"+BU+" 2 LoadRunner + 4 JMeter",details:{test_cases:[{id:"TC-4521-001",title:"Create Order via OPUS",risk:"HIGH",harness:"LoadRunner",protocol:"Web HTTP/HTML",systems:["OPUS","CSI","TLG","BSSe"]},{id:"TC-4521-002",title:"Order Status via OPUS",risk:"MEDIUM",harness:"JMeter",protocol:"REST/JSON",systems:["OPUS","CSI","TLG"]},{id:"TC-4521-003",title:"Billing Inquiry",risk:"MEDIUM",harness:"JMeter",protocol:"REST/JSON",systems:["CSI","TLG","BSSe"]},{id:"TC-4522-001",title:"Customer Profile Update",risk:"MEDIUM",harness:"JMeter",protocol:"REST/JSON",systems:["OPUS","CSI","TLG"]},{id:"TC-4522-002",title:"Payment via CAS",risk:"HIGH",harness:"JMeter",protocol:"REST/JSON",systems:["OPUS","CAS/iCAS","BSSe"]},{id:"TC-4522-003",title:"Async Order via GDDN",risk:"MEDIUM",harness:"JMeter",protocol:"Solace MQ",systems:["CSI","GDDN","TLG","OMS"]}],sla_targets:[{txn:"Create_Order_OPUS",p90:3000,p95:5000,err:1.0},{txn:"Order_Status_Query",p90:800,p95:1200,err:0.5},{txn:"Billing_Inquiry",p90:1000,p95:1500,err:0.5},{txn:"Customer_Profile_Update",p90:1200,p95:2000,err:1.0},{txn:"Payment_Processing",p90:2000,p95:3000,err:0.5},{txn:"Async_Order_Event",p90:5000,p95:8000,err:2.0}]}}},
test_planning:{duration:3000,logs:[{delay:0,lv:"INFO",m:"Phase 2 starting"},{delay:200,lv:"INFO",m:"Injecting HITL context"},{delay:500,lv:"TOOL",m:AR+" read_app_config()"},{delay:900,lv:"TOOL",m:AR+" get_service_metrics(168h)"},{delay:1400,lv:"LLM",m:"GPT-4o "+AR+" 4 scenarios (8192 tok)"},{delay:2000,lv:"TOOL",m:AR+" create_jira_story()"},{delay:2900,lv:"INFO",m:"Phase 2 done"}],result:{duration_seconds:62.8,summary:"Sprint 26.3 Test Plan\n"+BU+" LOAD: 30m @ 450 TPS\n"+BU+" STRESS: 45m "+AR+" 900 TPS\n"+BU+" ENDURANCE: 240m @ 450 TPS\n"+BU+" SPIKE: 15m 3x burst IDP",details:{scenarios:[{type:"LOAD",duration:"30 min",tps:450,vusers:150,desc:"Baseline SLA validation"},{type:"STRESS",duration:"45 min",tps:"450"+AR+"900",vusers:"150"+AR+"300",desc:"Find breakpoint"},{type:"ENDURANCE",duration:"240 min",tps:450,vusers:150,desc:"4hr sustained"},{type:"SPIKE",duration:"15 min",tps:"450"+AR+"1350",vusers:"150"+AR+"450",desc:"3x burst IDP"}],workload_mix:[{txn:"Create_Order_OPUS",pct:15,tps:67.5},{txn:"Order_Status_Query",pct:30,tps:135},{txn:"Billing_Inquiry",pct:25,tps:112.5},{txn:"Customer_Profile_Update",pct:10,tps:45},{txn:"Payment_Processing",pct:10,tps:45},{txn:"Async_Order_Event",pct:10,tps:45}]}}},
env_triage:{duration:3000,logs:[{delay:0,lv:"INFO",m:"Phase 3 starting"},{delay:400,lv:"TOOL",m:AR+" read_env_reference()"},{delay:800,lv:"TOOL",m:AR+" check_aks_deployment()"},{delay:1200,lv:"TOOL",m:AR+" check_app_gateway()"},{delay:1700,lv:"WARN",m:"MISMATCH billing-api "+AR+" QC3!"},{delay:2100,lv:"WARN",m:"MISMATCH gddn.SOLACE_VPN "+AR+" qc3-vpn"},{delay:2700,lv:"INFO",m:"22/24 passed, 2 mismatches"}],result:{duration_seconds:18.4,summary:"Config: 24 checks\n"+BU+" PASSED: 22 | FAILED: 2\n\n  X billing-api.BSSE_ENDPOINT "+AR+" bsse-qc3:9443\n  X gddn.SOLACE_VPN "+AR+" qc3-vpn",details:{checks:[{app:"opus-web",field:"CSI_GATEWAY_URL",expected:"csi-perf:8443",actual:"csi-perf:8443",pass:true},{app:"csi-gw",field:"TLG_ENDPOINT",expected:"tlg-perf:9443",actual:"tlg-perf:9443",pass:true},{app:"billing-api",field:"BSSE_ENDPOINT",expected:"bsse-perf:9443",actual:"bsse-qc3:9443",pass:false},{app:"gddn-msg",field:"SOLACE_VPN",expected:"perf-vpn",actual:"qc3-vpn",pass:false},{app:"tlg",field:"DB_CONNECTION",expected:"oracle-perf/TLG",actual:"oracle-perf/TLG",pass:true},{app:"app-gw",field:"pool_csi",expected:"csi-perf",actual:"csi-perf",pass:true}]}}},
script_data:{duration:4000,logs:[{delay:0,lv:"INFO",m:"Phase 4 starting"},{delay:400,lv:"TOOL",m:AR+" generate_vugen('Create_Order')"},{delay:900,lv:"TOOL",m:AR+" generate_jmeter('Billing')"},{delay:1400,lv:"TOOL",m:AR+" generate_jmeter('Async_GDDN','solace')"},{delay:1900,lv:"INFO",m:"6/6 syntax+dry-run passed"},{delay:2400,lv:"TOOL",m:AR+" provision_data('customers',50K)"},{delay:2900,lv:"TOOL",m:AR+" provision_data('orders',100K)"},{delay:3500,lv:"INFO",m:"Phase 4 done "+DA+" 6 scripts, 355K rows"}],result:{duration_seconds:127.6,summary:"Scripts: 6 (2 VuGen, 4 JMeter) "+DA+" all passed\nData: 355K records",details:{scripts:[{name:"Create_Order_OPUS.c",harness:"LR",protocol:"HTTP/HTML",corr:8,dry:2340,status:"passed"},{name:"Order_Status.c",harness:"LR",protocol:"HTTP/HTML",corr:4,dry:680,status:"passed"},{name:"Billing_Inquiry.jmx",harness:"JMeter",protocol:"REST",corr:2,dry:890,status:"passed"},{name:"Payment_CAS.jmx",harness:"JMeter",protocol:"REST",corr:5,dry:1650,status:"passed"},{name:"Async_GDDN.jmx",harness:"JMeter",protocol:"Solace",corr:1,dry:340,status:"passed"}],bulk:[{ent:"Customers",qty:"50K",meth:"API"+AR+"TLG",dur:"18m"},{ent:"Orders",qty:"100K",meth:"SQL"+AR+"Oracle",dur:"7m"},{ent:"Billing",qty:"200K",meth:"SQL"+AR+"BSSe",dur:"12m"},{ent:"Solace",qty:"5K",meth:"JMS",dur:"2m"}]}}},
execution:{duration:5000,logs:[{delay:0,lv:"INFO",m:"Phase 5 starting"},{delay:300,lv:"INFO",m:"Pre-flight: no drift"},{delay:600,lv:"TOOL",m:AR+" start_lre(LOAD)"},{delay:1100,lv:"INFO",m:"LOAD: 487 TPS, 0.3% err, SLAs met"},{delay:1500,lv:"TOOL",m:AR+" start_lre(STRESS)"},{delay:2000,lv:"ERROR",m:"TLG pool exhausted (30/30) at 612 TPS"},{delay:2300,lv:"TOOL",m:AR+" create_defect "+AR+" TELECOM-4587"},{delay:2700,lv:"INFO",m:"Pool 30"+AR+"75. ENDURANCE starting."},{delay:3200,lv:"INFO",m:"ENDURANCE 4hr: PASSED"},{delay:3700,lv:"INFO",m:"SPIKE: 3"+AR+"9 pods 94s, PASSED"},{delay:4800,lv:"INFO",m:"Phase 5 done"}],result:{duration_seconds:18420,summary:"LOAD: PASSED 487 TPS\nSTRESS: BREAK 612 TPS (TLG pool)\nENDURANCE: PASSED 4hr\nSPIKE: PASSED\n\nDefect: TELECOM-4587 (MAJOR)",details:{peak:{tps:487,vusers:150,err:"0.3%"},brk:{tps:612,vusers:204,cause:"TLG conn pool"},anomalies:[{sev:"CRITICAL",src:"Dynatrace",sys:"TLG",desc:"Pool exhausted (30/30)",jira:"TELECOM-4587"},{sev:"ERROR",src:"ELK",sys:"CSI",desc:"503 from TLG (142/60s)",jira:DA},{sev:"WARNING",src:"Prometheus",sys:"IDP",desc:"JVM heap 78%",jira:DA}]}}},
reporting:{duration:2500,logs:[{delay:0,lv:"INFO",m:"Phase 6 starting"},{delay:400,lv:"TOOL",m:AR+" get_baselines()"},{delay:900,lv:"LLM",m:"GPT-4o "+AR+" CONDITIONAL GO"},{delay:1400,lv:"TOOL",m:AR+" generate_report()"},{delay:1800,lv:"TOOL",m:AR+" upload_sharepoint()"},{delay:2200,lv:"INFO",m:"Phase 6 done "+DA+" published"}],result:{duration_seconds:34.2,summary:"CONDITIONAL GO\nSLA: 6/6 passed | Baseline: improved\nDefect: TELECOM-4587 (MAJOR)\nSharePoint+Snowflake: done",details:{sla:[{txn:"Create_Order",sla:3000,actual:2840,delta:"-8.4%",trend:UP+" improving"},{txn:"Order_Status",sla:800,actual:520,delta:"-10.3%",trend:UP+" improving"},{txn:"Billing",sla:1000,actual:780,delta:"+5.4%",trend:AR+" stable"},{txn:"Payment",sla:2000,actual:1680,delta:"+5.7%",trend:AR+" stable"},{txn:"Async_Order",sla:5000,actual:3200,delta:"-5.9%",trend:UP+" improving"}],defects:[{key:"TELECOM-4587",sev:"MAJOR",sys:"TLG",title:"Pool 30"+AR+"75 in PROD",status:"Open"}],verdict:"CONDITIONAL GO",condition:"TELECOM-4587 must be resolved in PROD"}}},
postmortem:{duration:2500,logs:[{delay:0,lv:"INFO",m:"Phase 7 starting"},{delay:400,lv:"LLM",m:"GPT-4o "+AR+" 4 issues, 3 lessons"},{delay:1000,lv:"TOOL",m:AR+" archive_snowflake()"},{delay:1500,lv:"TOOL",m:AR+" index_rag(3 lessons)"},{delay:2000,lv:"INFO",m:"Phase 7 done "+DA+" feedback loop active"},{delay:2400,lv:"INFO",m:"Pipeline complete "+DA+" 7/7"}],result:{duration_seconds:28.8,summary:"6.5hr lost (4 issues)\n"+BU+" Env: QC3 "+DA+" 3hr\n"+BU+" Tech: TLG pool "+DA+" 2hr\n"+BU+" Data: Dup IDs "+DA+" 1hr\n"+BU+" Tool: LRE "+DA+" 0.5hr\n\n3 lessons "+AR+" RAG",details:{entries:[{ph:"P3",cat:"Environment",t:"QC3 pointers",h:3.0},{ph:"P5",cat:"Technical",t:"TLG pool at 612 TPS",h:2.0},{ph:"P4",cat:"Data",t:"Duplicate IDs",h:1.0},{ph:"P5",cat:"Tooling",t:"LRE conflict",h:0.5}],lessons:[{title:"Validate env 24hr before exec",rec:"Run Phase 3 early for CSTEM time",tags:["environment","process"]},{title:"TLG pool must handle 2x peak",rec:"30 insufficient >600 TPS. PROD needs 75.",tags:["amdocs","capacity"]},{title:"Add dedup to bulk data",rec:"Unique constraint check post-provisioning",tags:["data","automation"]}]}}}
};
// Shared
const Badge=({status,large})=>{const s=STATUS[status]||STATUS.pending;return (<span style={{display:"inline-flex",alignItems:"center",gap:5,padding:large?"5px 14px":"3px 10px",borderRadius:20,fontSize:large?13:11,fontFamily:C.fontSans,fontWeight:700,background:s.bg,color:s.color,border:`1px solid ${s.border}`}}>{s.dot&&<span style={{width:6,height:6,borderRadius:"50%",background:s.color,animation:"pulse 1.5s infinite"}}/>}{s.label}</span>);};
const Sec=({title})=>(<div style={{fontSize:11,fontWeight:800,color:C.textSecondary,letterSpacing:"0.06em",textTransform:"uppercase",paddingBottom:8,borderBottom:`2px solid ${C.border}`,marginTop:4}}>{title}</div>);
const Card=({children,style})=>(<div style={{background:C.bgCard,borderRadius:12,padding:20,border:`1px solid ${C.border}`,boxShadow:"0 1px 3px rgba(0,0,0,0.04)",...style}}>{children}</div>);
function LogTerminal({logs}){const ref=useRef(null);useEffect(()=>{ref.current?.scrollTo({top:ref.current.scrollHeight,behavior:"smooth"});},[logs.length]);const lc={INFO:"#0077a8",WARN:"#b37400",ERROR:C.error,TOOL:"#5a67d8",LLM:"#b83280",HITL:C.purple};return (<div ref={ref} style={{background:"#1a1a2e",borderRadius:10,padding:16,fontFamily:C.fontMono,fontSize:11,lineHeight:1.8,maxHeight:400,overflowY:"auto"}}>{logs.length===0?<div style={{color:"#6b7280"}}>Waiting...</div>:logs.map((l,i)=>(<div key={i} style={{display:"flex",gap:10,animation:"fadeIn 0.3s ease"}}><span style={{color:"#6b7280",flexShrink:0}}>{l.ts}</span><span style={{color:lc[l.lv]||"#9ca3af",flexShrink:0,width:36,textAlign:"right",fontWeight:600}}>{l.lv}</span><span style={{color:l.lv==="WARN"?"#fbbf24":l.lv==="ERROR"?"#f87171":"#e5e7eb"}}>{l.m}</span></div>))}</div>);}
function DT({columns,rows}){return (<div style={{overflowX:"auto",borderRadius:8,border:`1px solid ${C.border}`}}><table style={{width:"100%",borderCollapse:"collapse",fontFamily:C.fontMono,fontSize:12}}><thead><tr style={{background:C.bgMuted}}>{columns.map(c=><th key={c} style={{padding:"10px 14px",textAlign:"left",color:C.textSecondary,fontWeight:700,fontSize:11,fontFamily:C.fontSans,borderBottom:`1px solid ${C.border}`}}>{c}</th>)}</tr></thead><tbody>{rows}</tbody></table></div>);}
function AgentPromptViewer({phaseId}){const[open,setOpen]=useState(false);const p=AGENT_PROMPTS[phaseId];if(!p) return null;return (<div style={{background:C.white,borderRadius:10,border:`1px solid ${open?C.attBlue+"40":C.border}`,overflow:"hidden",transition:"border-color 0.2s"}}><button onClick={()=>setOpen(!open)} style={{width:"100%",display:"flex",alignItems:"center",justifyContent:"space-between",padding:"14px 16px",border:"none",background:"transparent",cursor:"pointer",textAlign:"left"}}><div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:28,height:28,borderRadius:8,background:open?C.attBlue:C.bgMuted,display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,color:open?"white":C.textMuted,fontFamily:C.fontMono,fontWeight:700}}>{"{ }"}</div><div><div style={{fontSize:13,fontWeight:700}}>Agent Context (Prompt Sent to LLM)</div><div style={{fontSize:11,color:C.textMuted,marginTop:1}}>{p.role}</div></div></div><span style={{fontSize:16,color:C.textMuted,transition:"transform 0.2s",transform:open?"rotate(180deg)":"none"}}>{"v"}</span></button>{open&&<div style={{padding:"0 16px 16px",animation:"fadeIn 0.2s ease"}}><div style={{marginBottom:12}}><div style={{fontSize:10,fontWeight:700,color:C.attBlueDark,letterSpacing:"0.06em",textTransform:"uppercase",marginBottom:6}}>System Prompt</div><pre style={{background:C.bgMuted,borderRadius:8,padding:12,fontFamily:C.fontMono,fontSize:11,lineHeight:1.7,whiteSpace:"pre-wrap",border:`1px solid ${C.border}`,margin:0,maxHeight:250,overflowY:"auto"}}>{p.system}</pre></div><div><div style={{fontSize:10,fontWeight:700,color:C.attBlueDark,letterSpacing:"0.06em",textTransform:"uppercase",marginBottom:6}}>Input Prompt</div><pre style={{background:C.attBlueFaint,borderRadius:8,padding:12,fontFamily:C.fontMono,fontSize:11,lineHeight:1.7,whiteSpace:"pre-wrap",border:`1px solid ${C.attBlue}20`,margin:0}}>{p.input}</pre></div></div>}</div>);}

// ═══════════════════════════════════════════════════════════════
// LANDING PAGE
// ═══════════════════════════════════════════════════════════════
function LandingPage({onLaunch}){
  const[contextIds,setContextIds]=useState([]);const[selectedApps,setSelectedApps]=useState([]);
  const[iv,setIv]=useState("");const[it,setIt]=useState("PID");const ref=useRef(null);
  const[storyKeys,setStoryKeys]=useState("TELECOM-4521, TELECOM-4522");const[sprint,setSprint]=useState("Sprint 26.3");
  const[appFilter,setAppFilter]=useState("");const[dateSort,setDateSort]=useState("desc");const[statusFilter,setStatusFilter]=useState("all");
  const add=()=>{const v=iv.trim().toUpperCase();if(!v)return;let t=it;if(v.startsWith("PID"))t="PID";else if(v.startsWith("E1"))t="E1";if(contextIds.some(c=>c.id===v)){setIv("");return;}setContextIds([...contextIds,{id:v,type:t,label:"",status:"pending"}]);setIv("");ref.current?.focus();};
  const rm=(id)=>setContextIds(contextIds.filter(c=>c.id!==id));
  const kd=(e)=>{if(e.key==="Enter"){e.preventDefault();add();}if(e.key==="Backspace"&&iv===""&&contextIds.length>0)rm(contextIds[contextIds.length-1].id);};
  const lk=(i)=>{const u=[...contextIds];u[i]={...u[i],status:"searching"};setContextIds(u);setTimeout(()=>{const L={PID:["CTx Billing Mod","OPUS Mobile Upgrade","Order Mgmt"],E1:["SF/Mulesoft Migration","TLG Backend","GDDN Messaging"]};const p=L[contextIds[i]?.type]||L.PID;const u2=[...contextIds];u2[i]={...u2[i],status:"indexed",label:p[Math.floor(Math.random()*p.length)]};setContextIds(u2);},500+Math.random()*400);};
  const toggleApp=(id)=>setSelectedApps(prev=>prev.includes(id)?prev.filter(a=>a!==id):[...prev,id]);
  const canLaunch=contextIds.length>0&&selectedApps.length>0&&storyKeys.trim();
  const si={pending:{s:"○",c:C.textMuted},searching:{s:"◌",c:C.attBlue},indexed:{s:"●",c:C.success}};
  const tc={Frontend:C.attBlue,Middleware:"#5a67d8",Backend:C.warning,Other:C.textMuted};
  const verdictColors={GO:C.success,"CONDITIONAL":C.warning,"NO-GO":C.error};

  const filteredRuns=useMemo(()=>{
    let r=[...PAST_RUNS];
    if(statusFilter!=="all") r=r.filter(x=>statusFilter==="completed"?x.status==="completed":x.status==="failed");
    if(appFilter) r=r.filter(x=>x.apps.some(a=>a.toLowerCase().includes(appFilter.toLowerCase())));
    r.sort((a,b)=>dateSort==="desc"?b.date.localeCompare(a.date):a.date.localeCompare(b.date));
    return r;
  },[appFilter,dateSort,statusFilter]);

  return (<div style={{maxWidth:1100,margin:"0 auto",padding:"32px 24px",display:"flex",flexDirection:"column",gap:28}}>
    {/* Header */}
    <div><div style={{fontSize:28,fontWeight:800,color:C.textPrimary,marginBottom:4}}>Performance Test Pipeline</div><div style={{fontSize:14,color:C.textSecondary}}>Configure and launch a new test run, or review past executions</div></div>

    {/* New Run Config */}
    <Card style={{border:`2px solid ${C.attBlue}30`,boxShadow:`0 4px 20px ${C.attBlue}08`}}>
      <div style={{fontSize:18,fontWeight:800,color:C.textPrimary,marginBottom:20}}>New Pipeline Run</div>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,marginBottom:20}}>
        <div><div style={{fontSize:12,fontWeight:700,color:C.textSecondary,marginBottom:6}}>Jira Story Keys <span style={{color:C.error}}>*</span></div><input value={storyKeys} onChange={e=>setStoryKeys(e.target.value)} placeholder="TELECOM-1234, TELECOM-1235" style={{width:"100%",boxSizing:"border-box",padding:"10px 14px",borderRadius:8,border:`1px solid ${C.border}`,background:C.bgMuted,fontFamily:C.fontMono,fontSize:13,outline:"none"}} onFocus={e=>e.target.style.borderColor=C.attBlue} onBlur={e=>e.target.style.borderColor=C.border}/></div>
        <div><div style={{fontSize:12,fontWeight:700,color:C.textSecondary,marginBottom:6}}>Sprint</div><input value={sprint} onChange={e=>setSprint(e.target.value)} placeholder="Sprint 26.3" style={{width:"100%",boxSizing:"border-box",padding:"10px 14px",borderRadius:8,border:`1px solid ${C.border}`,background:C.bgMuted,fontFamily:C.fontMono,fontSize:13,outline:"none"}} onFocus={e=>e.target.style.borderColor=C.attBlue} onBlur={e=>e.target.style.borderColor=C.border}/></div>
      </div>

      {/* Context IDs */}
      <div style={{marginBottom:20,padding:16,borderRadius:10,background:C.attBlueFaint,border:`1px solid ${C.attBlue}25`}}>
        <div style={{fontSize:14,fontWeight:800,marginBottom:2}}>Project Context IDs <span style={{color:C.error,fontSize:12}}>*</span></div>
        <div style={{fontSize:12,color:C.textSecondary,marginBottom:12}}>PIDs or E1 IDs to seed the RAG search with project documentation</div>
        {contextIds.length>0&&<div style={{display:"flex",flexWrap:"wrap",gap:8,marginBottom:12}}>{contextIds.map((cx,i)=>{const s=si[cx.status]||si.pending;return (<div key={cx.id} style={{display:"inline-flex",alignItems:"center",gap:6,padding:"6px 8px 6px 10px",borderRadius:8,fontSize:12,fontFamily:C.fontMono,fontWeight:600,background:cx.status==="indexed"?C.successBg:C.white,color:cx.status==="indexed"?"#065f46":C.textPrimary,border:`1px solid ${cx.status==="indexed"?C.successBorder:C.border}`}}><span style={{color:s.c,fontSize:10,animation:cx.status==="searching"?"pulse 1s infinite":"none"}}>{s.s}</span><span style={{padding:"1px 5px",borderRadius:4,fontSize:9,fontWeight:800,background:cx.type==="PID"?C.attBlue+"18":C.purple+"18",color:cx.type==="PID"?C.attBlueDark:C.purple}}>{cx.type}</span><span>{cx.id}</span>{cx.label&&<span style={{color:C.textSecondary,fontFamily:C.fontSans,fontWeight:400,fontSize:11}}>{DA} {cx.label}</span>}{cx.status==="pending"&&<button onClick={()=>lk(i)} style={{padding:"2px 7px",borderRadius:4,border:`1px solid ${C.attBlue}40`,background:C.attBlueLight,color:C.attBlueDark,fontSize:10,fontWeight:700,cursor:"pointer"}}>Search</button>}<button onClick={()=>rm(cx.id)} style={{width:18,height:18,border:"none",borderRadius:4,background:"transparent",color:C.textMuted,fontSize:15,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center"}} onMouseEnter={e=>{e.target.style.background=C.errorBg;e.target.style.color=C.error}} onMouseLeave={e=>{e.target.style.background="transparent";e.target.style.color=C.textMuted}}>x</button></div>);})}</div>}
        <div style={{display:"flex",gap:8,alignItems:"center"}}><div style={{display:"flex",borderRadius:8,overflow:"hidden",border:`1px solid ${C.border}`,flexShrink:0}}>{["PID","E1"].map(t=><button key={t} onClick={()=>setIt(t)} style={{padding:"8px 14px",border:"none",fontSize:12,fontWeight:700,fontFamily:C.fontMono,cursor:"pointer",background:it===t?(t==="PID"?C.attBlue:C.purple):C.white,color:it===t?"white":C.textMuted}}>{t}</button>)}</div><input ref={ref} value={iv} onChange={e=>setIv(e.target.value)} onKeyDown={kd} placeholder={it==="PID"?"PID-2026-0481":"E1-88432"} style={{flex:1,padding:"8px 14px",borderRadius:8,border:`1px solid ${C.border}`,background:C.white,fontFamily:C.fontMono,fontSize:13,fontWeight:600,outline:"none"}} onFocus={e=>e.target.style.borderColor=C.attBlue} onBlur={e=>e.target.style.borderColor=C.border}/><button onClick={add} disabled={!iv.trim()} style={{padding:"8px 18px",borderRadius:8,border:"none",background:iv.trim()?C.attBlue:C.bgMuted,color:iv.trim()?"white":C.textMuted,fontWeight:700,fontSize:13,cursor:iv.trim()?"pointer":"default",flexShrink:0}}>+ Add</button></div>
      </div>

      {/* App Selection */}
      <div style={{marginBottom:20}}>
        <div style={{fontSize:14,fontWeight:800,marginBottom:2}}>Applications Under Test <span style={{color:C.error,fontSize:12}}>*</span></div>
        <div style={{fontSize:12,color:C.textSecondary,marginBottom:12}}>Select systems to include in testing scope</div>
        <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(200px,1fr))",gap:8}}>{APPS.map(app=>{const sel=selectedApps.includes(app.id);const tcc=tc[app.tier]||C.textMuted;return (<div key={app.id} onClick={()=>toggleApp(app.id)} style={{display:"flex",alignItems:"center",gap:10,padding:"10px 12px",borderRadius:10,cursor:"pointer",background:sel?C.attBlueFaint:C.white,border:`2px solid ${sel?C.attBlue:C.border}`,transition:"all 0.15s"}}><div style={{width:32,height:32,borderRadius:8,display:"flex",alignItems:"center",justifyContent:"center",fontSize:14,fontWeight:800,background:sel?C.attBlue:C.bgMuted,color:sel?"white":C.textMuted}}>{app.icon}</div><div style={{flex:1,minWidth:0}}><div style={{fontSize:12,fontWeight:700,color:sel?C.textPrimary:C.textSecondary}}>{app.name}</div><div style={{display:"flex",gap:4,marginTop:2}}><span style={{padding:"1px 5px",borderRadius:3,fontSize:9,fontWeight:700,background:tcc+"14",color:tcc}}>{app.tier}</span><span style={{padding:"1px 5px",borderRadius:3,fontSize:9,background:C.bgMuted,color:C.textMuted}}>{app.protocol}</span></div></div><div style={{width:20,height:20,borderRadius:6,border:`2px solid ${sel?C.attBlue:C.border}`,background:sel?C.attBlue:"white",display:"flex",alignItems:"center",justifyContent:"center"}}>{sel&&<span style={{color:"white",fontSize:12,fontWeight:800}}>{"✓"}</span>}</div></div>);})}</div>
      </div>

      {/* Launch */}
      <button onClick={()=>onLaunch({storyKeys,sprint,contextIds,selectedApps})} disabled={!canLaunch} style={{width:"100%",padding:"16px 0",borderRadius:10,border:"none",background:canLaunch?C.attBlue:C.bgMuted,color:canLaunch?"white":C.textMuted,fontWeight:800,fontSize:16,cursor:canLaunch?"pointer":"default",boxShadow:canLaunch?`0 4px 12px ${C.attBlue}30`:"none",transition:"all 0.2s"}} onMouseEnter={e=>{if(canLaunch)e.target.style.background=C.attBlueDark}} onMouseLeave={e=>{if(canLaunch)e.target.style.background=C.attBlue}}>{canLaunch?`Launch Pipeline (${contextIds.length} ID${contextIds.length!==1?"s":""}, ${selectedApps.length} app${selectedApps.length!==1?"s":""})`:contextIds.length===0?"Add at least one Context ID":"Select at least one Application"}</button>
    </Card>

    {/* Past Runs */}
    <div>
      <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:14}}>
        <div style={{fontSize:18,fontWeight:800}}>Test Run History</div>
        <div style={{display:"flex",gap:8,alignItems:"center"}}>
          <input value={appFilter} onChange={e=>setAppFilter(e.target.value)} placeholder="Filter by app..." style={{padding:"7px 12px",borderRadius:8,border:`1px solid ${C.border}`,fontSize:12,fontFamily:C.fontSans,outline:"none",width:160}} onFocus={e=>e.target.style.borderColor=C.attBlue} onBlur={e=>e.target.style.borderColor=C.border}/>
          <div style={{display:"flex",borderRadius:8,overflow:"hidden",border:`1px solid ${C.border}`}}>{[{k:"all",l:"All"},{k:"completed",l:"Completed"},{k:"failed",l:"Failed"}].map(f=>(<button key={f.k} onClick={()=>setStatusFilter(f.k)} style={{padding:"7px 12px",border:"none",fontSize:11,fontWeight:700,cursor:"pointer",background:statusFilter===f.k?C.attBlue:C.white,color:statusFilter===f.k?"white":C.textMuted}}>{f.l}</button>))}</div>
          <button onClick={()=>setDateSort(p=>p==="desc"?"asc":"desc")} style={{padding:"7px 12px",borderRadius:8,border:`1px solid ${C.border}`,background:C.white,fontSize:11,fontWeight:700,cursor:"pointer",color:C.textSecondary}}>{dateSort==="desc"?"Newest first":"Oldest first"}</button>
        </div>
      </div>
      <DT columns={["Date","Sprint","Stories","Applications","Phase","Duration","Verdict","Status"]} rows={filteredRuns.map((r,i)=>(<tr key={i} style={{borderBottom:`1px solid ${C.borderLight}`}}>
        <td style={{padding:"10px 14px",fontFamily:C.fontMono,color:C.textPrimary,fontWeight:600}}>{r.date}</td>
        <td style={{padding:"10px 14px",color:C.textSecondary}}>{r.sprint}</td>
        <td style={{padding:"10px 14px",color:C.attBlue,fontSize:11}}>{r.stories.join(", ")}</td>
        <td style={{padding:"10px 14px",fontSize:11}}><div style={{display:"flex",gap:4,flexWrap:"wrap"}}>{r.apps.map(a=>(<span key={a} style={{padding:"1px 6px",borderRadius:4,fontSize:9,fontWeight:600,background:C.bgMuted,color:C.textSecondary}}>{a}</span>))}</div></td>
        <td style={{padding:"10px 14px",fontFamily:C.fontMono,color:r.phase===7?C.success:C.warning}}>{r.phase}/7</td>
        <td style={{padding:"10px 14px",fontFamily:C.fontMono,color:C.textSecondary}}>{r.duration}</td>
        <td style={{padding:"10px 14px"}}>{r.verdict!==DA?<span style={{padding:"2px 8px",borderRadius:4,fontSize:10,fontWeight:700,background:(verdictColors[r.verdict]||C.textMuted)+"14",color:verdictColors[r.verdict]||C.textMuted}}>{r.verdict}</span>:<span style={{color:C.textMuted}}>-</span>}</td>
        <td style={{padding:"10px 14px"}}><Badge status={r.status==="failed"?"pending":r.status}/></td>
      </tr>))}/>
    </div>
  </div>);
}

// ═══════════════════════════════════════════════════════════════
// PHASE DETAIL RENDERER
// ═══════════════════════════════════════════════════════════════
function PhaseDetail({phase,result}){
  if(!result||result.status==="pending") return null;
  if(result.status==="running") return (<div style={{padding:48,textAlign:"center",color:C.attBlue}}><span style={{animation:"pulse 1.5s infinite",display:"inline-block"}}>Agent is working...</span></div>);
  const d=result.details;const rc={HIGH:C.error,MEDIUM:C.warning,LOW:C.success};const tc={LOAD:C.attBlue,STRESS:C.error,ENDURANCE:C.warning,SPIKE:C.purple};const mx=["#00A8E0","#0077a8","#0faa6c","#e5920a","#dc3545","#6f42c1"];
  return (<div style={{display:"flex",flexDirection:"column",gap:20}}>
    {result.hitl_context&&<div style={{background:C.bgMuted,borderRadius:10,padding:"12px 16px",border:`1px solid ${C.border}`}}><div style={{display:"flex",alignItems:"center",gap:6,marginBottom:6}}><span style={{color:C.success}}>{"✓"}</span><span style={{fontSize:12,fontWeight:700}}>Context Passed to Next Phase</span></div><div style={{fontSize:12,color:C.textSecondary,lineHeight:1.6}}>{result.hitl_context}</div></div>}
    <pre style={{background:C.bgMuted,borderRadius:8,padding:16,fontFamily:C.fontMono,fontSize:12,lineHeight:1.7,whiteSpace:"pre-wrap",border:`1px solid ${C.border}`,margin:0}}>{result.summary}</pre>
    {phase.id==="story_analysis"&&d&&(<><Sec title="Test Cases"/><DT columns={["ID","Title","Risk","Harness","Protocol","Systems"]} rows={d.test_cases.map((t,i)=>(<tr key={i} style={{borderBottom:`1px solid ${C.borderLight}`}}><td style={{padding:"10px 14px",color:C.attBlue,fontWeight:600}}>{t.id}</td><td style={{padding:"10px 14px",fontFamily:C.fontSans}}>{t.title}</td><td style={{padding:"10px 14px"}}><span style={{padding:"2px 8px",borderRadius:4,fontSize:11,fontWeight:700,color:rc[t.risk],background:rc[t.risk]+"14"}}>{t.risk}</span></td><td style={{padding:"10px 14px",color:C.textSecondary}}>{t.harness}</td><td style={{padding:"10px 14px",color:C.textSecondary}}>{t.protocol}</td><td style={{padding:"10px 14px",color:C.textMuted,fontSize:11}}>{t.systems.join(" "+AR+" ")}</td></tr>))}/></>)}
    {phase.id==="test_planning"&&d&&(<><Sec title="Scenarios"/><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(200px,1fr))",gap:10}}>{d.scenarios.map((s,i)=>(<Card key={i} style={{borderTop:`4px solid ${tc[s.type]||C.attBlue}`,padding:14}}><div style={{fontSize:13,fontWeight:800,color:tc[s.type],marginBottom:4}}>{s.type}</div><div style={{fontSize:12,marginBottom:6}}>{s.desc}</div><div style={{fontSize:11,color:C.textSecondary,fontFamily:C.fontMono}}>{s.duration} | {s.tps} TPS | {s.vusers} VU</div></Card>))}</div><Sec title="Workload Mix"/><div style={{display:"flex",borderRadius:6,overflow:"hidden",height:28,marginBottom:10}}>{d.workload_mix.map((m,i)=>(<div key={i} style={{width:`${m.pct}%`,background:mx[i%mx.length],display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,fontFamily:C.fontMono,fontWeight:700,color:"white",borderRight:i<d.workload_mix.length-1?"2px solid white":"none"}}>{m.pct>=12?m.pct+"%":""}</div>))}</div><div style={{display:"flex",flexWrap:"wrap",gap:"6px 16px"}}>{d.workload_mix.map((m,i)=>(<div key={i} style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:10,height:10,borderRadius:3,background:mx[i%mx.length]}}/><span style={{fontSize:11,fontFamily:C.fontMono,color:C.textSecondary}}>{m.txn.replace(/_/g," ")} {DA} {m.tps}</span></div>))}</div></>)}
    {phase.id==="env_triage"&&d&&(<><Sec title="Config Checks"/><DT columns={["","App","Field","Expected","Actual"]} rows={d.checks.map((c,i)=>(<tr key={i} style={{borderBottom:`1px solid ${C.borderLight}`,background:!c.pass?C.errorBg:"transparent"}}><td style={{padding:"10px 14px",fontSize:16,color:c.pass?C.success:C.error}}>{c.pass?"✓":"✗"}</td><td style={{padding:"10px 14px",fontWeight:600}}>{c.app}</td><td style={{padding:"10px 14px",color:C.attBlue}}>{c.field}</td><td style={{padding:"10px 14px",color:C.textSecondary}}>{c.expected}</td><td style={{padding:"10px 14px",color:c.pass?C.textSecondary:C.error,fontWeight:c.pass?400:700}}>{c.actual}</td></tr>))}/></>)}
    {phase.id==="script_data"&&d&&(<><Sec title="Scripts"/><DT columns={["Script","Harness","Protocol","Corr","Dry Run"]} rows={d.scripts.map((s,i)=>(<tr key={i} style={{borderBottom:`1px solid ${C.borderLight}`}}><td style={{padding:"10px 14px",color:C.attBlue,fontWeight:600,fontSize:11}}>{s.name}</td><td style={{padding:"10px 14px",color:C.textSecondary}}>{s.harness}</td><td style={{padding:"10px 14px",color:C.textSecondary}}>{s.protocol}</td><td style={{padding:"10px 14px"}}>{s.corr}</td><td style={{padding:"10px 14px",fontFamily:C.fontMono}}>{s.dry}ms</td></tr>))}/><Sec title="Bulk Data"/><DT columns={["Entity","Qty","Method","Time"]} rows={d.bulk.map((b,i)=>(<tr key={i} style={{borderBottom:`1px solid ${C.borderLight}`}}><td style={{padding:"10px 14px",fontWeight:600}}>{b.ent}</td><td style={{padding:"10px 14px",color:C.attBlue,fontFamily:C.fontMono}}>{b.qty}</td><td style={{padding:"10px 14px",color:C.textSecondary}}>{b.meth}</td><td style={{padding:"10px 14px",fontFamily:C.fontMono}}>{b.dur}</td></tr>))}/></>)}
    {phase.id==="execution"&&d&&(<><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:10}}><Card style={{padding:14,borderTop:`3px solid ${C.success}`}}><div style={{fontSize:10,fontWeight:700,color:C.textMuted}}>PEAK</div><div style={{fontSize:22,fontWeight:800,color:C.success,fontFamily:C.fontMono}}>{d.peak.tps}<span style={{fontSize:11,color:C.textMuted}}> TPS</span></div></Card><Card style={{padding:14,borderTop:`3px solid ${C.error}`}}><div style={{fontSize:10,fontWeight:700,color:C.textMuted}}>BREAK</div><div style={{fontSize:22,fontWeight:800,color:C.error,fontFamily:C.fontMono}}>{d.brk.tps}<span style={{fontSize:11,color:C.textMuted}}> TPS</span></div></Card><Card style={{padding:14,borderTop:`3px solid ${C.attBlue}`}}><div style={{fontSize:10,fontWeight:700,color:C.textMuted}}>STABILITY</div><div style={{fontSize:22,fontWeight:800,color:C.attBlue}}>PASSED</div></Card><Card style={{padding:14,borderTop:`3px solid ${C.purple}`}}><div style={{fontSize:10,fontWeight:700,color:C.textMuted}}>SPIKE</div><div style={{fontSize:22,fontWeight:800,color:C.purple}}>PASSED</div></Card></div><Sec title="Anomalies"/><DT columns={["Sev","Source","System","Description","Jira"]} rows={d.anomalies.map((a,i)=>(<tr key={i} style={{borderBottom:`1px solid ${C.borderLight}`,background:a.sev==="CRITICAL"?C.errorBg:"transparent"}}><td style={{padding:"10px 14px"}}><span style={{padding:"2px 8px",borderRadius:4,fontSize:10,fontWeight:700,background:a.sev==="CRITICAL"?C.error+"14":a.sev==="ERROR"?C.warning+"14":C.bgMuted,color:a.sev==="CRITICAL"?C.error:a.sev==="ERROR"?C.warning:C.textMuted}}>{a.sev}</span></td><td style={{padding:"10px 14px",color:C.textSecondary}}>{a.src}</td><td style={{padding:"10px 14px",fontWeight:600}}>{a.sys}</td><td style={{padding:"10px 14px",fontSize:11}}>{a.desc}</td><td style={{padding:"10px 14px",color:C.attBlue,fontWeight:600}}>{a.jira}</td></tr>))}/></>)}
    {phase.id==="reporting"&&d&&(<><Card style={{background:C.warningBg,border:`1px solid ${C.warningBorder}`,padding:16}}><div style={{fontSize:28,fontWeight:800,color:C.warning}}>{d.verdict}</div><div style={{fontSize:13,marginTop:4}}>{d.condition}</div></Card><Sec title="SLA Compliance"/><DT columns={["Txn","SLA","Actual","Delta","Trend"]} rows={d.sla.map((s,i)=>(<tr key={i} style={{borderBottom:`1px solid ${C.borderLight}`}}><td style={{padding:"10px 14px",color:C.attBlue,fontWeight:600}}>{s.txn}</td><td style={{padding:"10px 14px",color:C.textMuted}}>{s.sla}ms</td><td style={{padding:"10px 14px",color:C.success,fontWeight:700}}>{s.actual}ms</td><td style={{padding:"10px 14px",color:s.delta.startsWith("-")?C.success:C.textSecondary,fontWeight:600}}>{s.delta}</td><td style={{padding:"10px 14px",color:C.textSecondary,fontSize:11}}>{s.trend}</td></tr>))}/></>)}
    {phase.id==="postmortem"&&d&&(<><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10}}><Card style={{padding:14,borderTop:`3px solid ${C.error}`}}><div style={{fontSize:10,fontWeight:700,color:C.textMuted}}>TIME LOST</div><div style={{fontSize:22,fontWeight:800,color:C.error,fontFamily:C.fontMono}}>6.5<span style={{fontSize:11,color:C.textMuted}}>hr</span></div></Card><Card style={{padding:14,borderTop:`3px solid ${C.warning}`}}><div style={{fontSize:10,fontWeight:700,color:C.textMuted}}>ISSUES</div><div style={{fontSize:22,fontWeight:800,color:C.warning,fontFamily:C.fontMono}}>4</div></Card><Card style={{padding:14,borderTop:`3px solid ${C.attBlue}`}}><div style={{fontSize:10,fontWeight:700,color:C.textMuted}}>LESSONS</div><div style={{fontSize:22,fontWeight:800,color:C.attBlue,fontFamily:C.fontMono}}>3</div></Card></div><Sec title="Issues"/><DT columns={["Ph","Cat","Issue","Hrs"]} rows={d.entries.map((e,i)=>(<tr key={i} style={{borderBottom:`1px solid ${C.borderLight}`}}><td style={{padding:"10px 14px",color:C.textSecondary}}>{e.ph}</td><td style={{padding:"10px 14px"}}><span style={{padding:"2px 8px",borderRadius:4,fontSize:10,fontWeight:700,background:e.cat==="Environment"?C.errorBg:e.cat==="Technical"?C.warningBg:C.bgMuted,color:e.cat==="Environment"?C.error:e.cat==="Technical"?C.warning:C.textSecondary}}>{e.cat}</span></td><td style={{padding:"10px 14px"}}>{e.t}</td><td style={{padding:"10px 14px",color:C.error,fontWeight:700,fontFamily:C.fontMono}}>{e.h}h</td></tr>))}/><Sec title={"Lessons "+AR+" RAG"}/>{d.lessons.map((l,i)=>(<Card key={i} style={{padding:14,borderLeft:`4px solid ${C.attBlue}`,marginTop:i?0:8}}><div style={{fontSize:13,fontWeight:700,marginBottom:4}}>{l.title}</div><div style={{fontSize:12,color:C.textSecondary,marginBottom:4}}>{l.rec}</div><div style={{display:"flex",gap:6}}>{l.tags.map(t=>(<span key={t} style={{padding:"2px 7px",borderRadius:4,fontSize:10,fontFamily:C.fontMono,background:C.attBlueLight,color:C.attBlueDark}}>{t}</span>))}</div></Card>))}<Card style={{background:C.successBg,border:`1px solid ${C.successBorder}`,padding:14,marginTop:4}}><div style={{display:"flex",alignItems:"center",gap:8}}><span style={{color:C.success,fontSize:16}}>{"✓"}</span><div><div style={{fontSize:12,fontWeight:700,color:"#065f46"}}>Feedback Loop Active</div><div style={{fontSize:11,color:C.textSecondary}}>3 lessons indexed to RAG for future runs</div></div></div></Card></>)}
  </div>);
}

// ═══════════════════════════════════════════════════════════════
// MAIN APP
// ═══════════════════════════════════════════════════════════════
export default function App(){
  const[page,setPage]=useState("landing"); // "landing" | "pipeline"
  const[ps,setPs]=useState(()=>Object.fromEntries(PHASES.map(p=>[p.id,{status:"pending"}])));
  const[ap,setAp]=useState("story_analysis");const[logs,setLogs]=useState([]);const[tab,setTab]=useState("details");
  const[hc,setHc]=useState({});const[runConfig,setRunConfig]=useState(null);
  const tr=useRef([]);
  const ts=()=>{const d=new Date();return `${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}:${String(d.getSeconds()).padStart(2,"0")}`;};
  const runP=useCallback((pid)=>{const sim=PHASE_SIMS[pid];if(!sim)return;setPs(p=>({...p,[pid]:{status:"running"}}));setAp(pid);setTab("logs");tr.current.forEach(clearTimeout);tr.current=[];sim.logs.forEach(l=>{const t=setTimeout(()=>{setLogs(pr=>[...pr,{ts:ts(),lv:l.lv,m:l.m}]);},l.delay);tr.current.push(t);});const t2=setTimeout(()=>{setPs(p=>({...p,[pid]:{status:"awaiting_approval",...sim.result}}));setLogs(pr=>[...pr,{ts:ts(),lv:"HITL",m:"Phase "+PHASES.find(pp=>pp.id===pid)?.num+" awaiting approval..."}]);setTab("details");},sim.duration);tr.current.push(t2);},[]);
  const approve=useCallback((pid)=>{const ctx=hc[pid]||"";setPs(p=>({...p,[pid]:{...p[pid],status:"completed",hitl_context:ctx}}));setLogs(pr=>{const o=[...pr,{ts:ts(),lv:"HITL",m:"Phase "+PHASES.find(pp=>pp.id===pid)?.num+" approved"}];if(ctx)o.push({ts:ts(),lv:"HITL",m:"Context: "+ctx.slice(0,80)+(ctx.length>80?"...":"")});return o;});const idx=PHASES.findIndex(p=>p.id===pid);if(idx<PHASES.length-1)setTimeout(()=>runP(PHASES[idx+1].id),500);},[hc,runP]);
  const handleLaunch=useCallback((config)=>{setRunConfig(config);setPage("pipeline");const ids=config.contextIds.map(c=>c.id).join(", ");const apps=config.selectedApps.map(id=>APPS.find(a=>a.id===id)?.name).join(", ");setLogs([{ts:ts(),lv:"INFO",m:"Pipeline initiated "+DA+" run-"+Date.now().toString(36)},{ts:ts(),lv:"INFO",m:"Stories: "+config.storyKeys+" | "+config.sprint},{ts:ts(),lv:"INFO",m:"Context IDs: "+ids},{ts:ts(),lv:"INFO",m:"Applications: "+apps}]);setTimeout(()=>runP("story_analysis"),300);},[runP]);

  const po=PHASES.find(p=>p.id===ap);const rs=ps[ap];const cc=Object.values(ps).filter(r=>r.status==="completed").length;const np=PHASES.find(p=>p.num===(po?.num||0)+1);

  return (<div style={{minHeight:"100vh",background:C.bg,fontFamily:C.fontSans}}>
    <style>{`@import url('https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&family=IBM+Plex+Mono:wght@400;600;700&display=swap');@keyframes pulse{0%,100%{opacity:1}50%{opacity:.35}}@keyframes fadeIn{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:translateY(0)}}::-webkit-scrollbar{width:7px}::-webkit-scrollbar-track{background:${C.bgMuted}}::-webkit-scrollbar-thumb{background:${C.border};border-radius:4px}*{box-sizing:border-box;margin:0;padding:0}`}</style>
    <header style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 28px",height:60,background:C.white,borderBottom:`1px solid ${C.border}`,boxShadow:"0 1px 4px rgba(0,0,0,0.04)"}}><div style={{display:"flex",alignItems:"center",gap:14,cursor:"pointer"}} onClick={()=>{if(page==="pipeline"&&cc===0)setPage("landing");}}><svg width="36" height="36" viewBox="0 0 36 36"><circle cx="18" cy="18" r="18" fill={C.attBlue}/><text x="18" y="22" textAnchor="middle" fill="white" fontFamily="Nunito" fontWeight="800" fontSize="13">PT</text></svg><div><div style={{fontSize:17,fontWeight:800,color:C.textPrimary}}>Agentic Pipeline Dashboard</div><div style={{fontSize:11,color:C.attBlue,fontWeight:700}}>CTx CQE Performance Engineering & Cybersecurity</div></div></div><div style={{display:"flex",alignItems:"center",gap:14}}>{page==="pipeline"&&<><div style={{display:"flex",alignItems:"center",gap:8,padding:"6px 14px",borderRadius:8,background:C.bgMuted,border:`1px solid ${C.border}`}}><span style={{width:7,height:7,borderRadius:"50%",background:cc===7?C.success:C.attBlue,animation:cc<7?"pulse 1.5s infinite":"none"}}/><span style={{fontSize:12,fontFamily:C.fontMono,color:C.textSecondary,fontWeight:600}}>{cc}/7</span></div><button onClick={()=>setPage("landing")} style={{padding:"8px 16px",borderRadius:8,border:`1px solid ${C.border}`,background:C.white,color:C.textSecondary,fontWeight:700,fontSize:12,cursor:"pointer"}}>Back to Home</button></>}</div></header>

    {page==="landing"&&<LandingPage onLaunch={handleLaunch}/>}

    {page==="pipeline"&&<>
    <div style={{display:"flex",alignItems:"center",padding:"14px 28px",background:C.white,borderBottom:`1px solid ${C.border}`,gap:6}}>{PHASES.map((p,i)=>{const s=ps[p.id]?.status||"pending";const sm=STATUS[s]||STATUS.pending;return (<div key={p.id} style={{display:"flex",alignItems:"center",flex:1,gap:6}}><div onClick={()=>setAp(p.id)} style={{width:30,height:30,borderRadius:"50%",display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,fontWeight:800,cursor:"pointer",background:s==="completed"?C.success:s==="pending"?C.bgMuted:sm.bg,color:s==="completed"?"white":s==="pending"?C.textMuted:sm.color,border:ap===p.id?`2px solid ${sm.color}`:"2px solid transparent",boxShadow:ap===p.id?`0 0 0 3px ${sm.color}20`:"none"}}>{s==="completed"?"✓":p.num}</div>{i<6&&<div style={{flex:1,height:3,borderRadius:2,background:s==="completed"?C.success:C.border}}/>}</div>);})}</div>
    <div style={{display:"grid",gridTemplateColumns:"260px 1fr",height:"calc(100vh - 120px)",overflow:"hidden"}}><div style={{background:C.white,borderRight:`1px solid ${C.border}`,padding:"18px 12px",overflowY:"auto"}}><div style={{padding:"0 8px",marginBottom:12}}><div style={{fontSize:11,fontWeight:800,color:C.textMuted,letterSpacing:"0.06em",textTransform:"uppercase",marginBottom:8}}>Pipeline</div>{runConfig&&<><div style={{display:"flex",gap:4,flexWrap:"wrap",marginBottom:6}}>{runConfig.storyKeys.split(",").map(k=>(<span key={k} style={{padding:"3px 8px",borderRadius:6,fontSize:10,fontFamily:C.fontMono,fontWeight:700,background:C.attBlueLight,color:C.attBlueDark}}>{k.trim()}</span>))}</div><div style={{fontSize:11,color:C.textMuted,marginBottom:4}}>{runConfig.sprint}</div><div style={{fontSize:10,color:C.textMuted}}>{runConfig.contextIds.length} IDs | {runConfig.selectedApps.length} apps</div></>}</div>
    {PHASES.map(p=>{const s=ps[p.id]?.status||"pending";const sm=STATUS[s]||STATUS.pending;const isA=ap===p.id;return (<div key={p.id} onClick={()=>setAp(p.id)} style={{display:"flex",alignItems:"center",gap:10,padding:"11px 12px",borderRadius:10,cursor:"pointer",background:isA?C.bgHover:"transparent",borderLeft:`3px solid ${isA?sm.color:"transparent"}`,marginBottom:2}}><div style={{width:30,height:30,borderRadius:8,display:"flex",alignItems:"center",justifyContent:"center",fontSize:13,fontWeight:800,background:s==="completed"?C.success+"14":s==="running"?C.attBlueLight:C.bgMuted,color:s==="completed"?C.success:s==="running"?C.attBlue:s==="awaiting_approval"?C.purple:C.textMuted,border:`1px solid ${s==="pending"?C.border:sm.color+"35"}`}}>{s==="completed"?"✓":p.num}</div><div style={{flex:1,minWidth:0}}><div style={{fontSize:13,fontWeight:isA?700:600,color:isA?C.textPrimary:C.textSecondary,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{p.label}</div></div><Badge status={s}/></div>);})}</div>
    <div style={{overflowY:"auto",padding:24,display:"flex",flexDirection:"column",gap:20}}>
      {po&&(<><div><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:4}}><span style={{fontSize:12,fontWeight:800,color:C.textMuted}}>PHASE {po.num}</span><Badge status={rs?.status||"pending"}/></div><div style={{fontSize:22,fontWeight:800}}>{po.label}</div><div style={{fontSize:13,color:C.textSecondary,marginTop:2}}>{PHASE_DESCS[po.id]}</div></div>
        {rs?.status==="awaiting_approval"&&(<Card style={{background:`linear-gradient(135deg,${C.purpleBg} 0%,#f0e8ff 100%)`,border:`2px solid ${C.purpleBorder}`}}>
          <div style={{display:"flex",alignItems:"center",gap:12,marginBottom:16}}><div style={{width:40,height:40,borderRadius:10,background:C.purple+"18",border:`2px solid ${C.purple}30`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:18,color:C.purple}}>{"⏸"}</div><div><div style={{fontSize:16,fontWeight:800}}>Approval Required</div><div style={{fontSize:13,color:C.purple,fontWeight:600}}>Phase {po.num}: {po.label}</div></div></div>
          <pre style={{background:C.white,borderRadius:8,padding:16,fontFamily:C.fontMono,fontSize:12,lineHeight:1.7,whiteSpace:"pre-wrap",margin:"0 0 16px 0",border:`1px solid ${C.purpleBorder}`,maxHeight:200,overflowY:"auto"}}>{rs.summary}</pre>
          <AgentPromptViewer phaseId={po.id}/>
          {np&&<div style={{background:C.white,borderRadius:10,padding:"14px 16px",border:`1px solid ${C.border}`,margin:"16px 0"}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:8}}><span style={{fontSize:12,color:C.attBlue}}>{"✎"}</span><div><div style={{fontSize:12,fontWeight:700}}>Additional Context for Phase {po.num+1} ({np.label})</div><div style={{fontSize:10,color:C.textMuted}}>Review the agent prompt above, then optionally steer the next phase</div></div></div><textarea value={hc[po.id]||""} onChange={e=>setHc(p=>({...p,[po.id]:e.target.value}))} placeholder={'e.g., "Focus on TLG flows" or "Extend endurance to 4hr"'} style={{width:"100%",boxSizing:"border-box",minHeight:64,padding:"10px 12px",borderRadius:8,border:`1px solid ${C.border}`,background:C.bgMuted,fontFamily:C.fontSans,fontSize:13,lineHeight:1.6,resize:"vertical",outline:"none"}} onFocus={e=>e.target.style.borderColor=C.attBlue} onBlur={e=>e.target.style.borderColor=C.border}/></div>}
          <button onClick={()=>approve(po.id)} style={{width:"100%",padding:"14px 0",borderRadius:8,border:"none",background:C.success,color:"white",fontWeight:800,fontSize:15,cursor:"pointer"}} onMouseEnter={e=>e.target.style.filter="brightness(1.1)"} onMouseLeave={e=>e.target.style.filter="none"}>{"✓ Approve & Continue"}</button>
        </Card>)}
        <div style={{display:"flex",alignItems:"center",gap:4,background:C.bgMuted,borderRadius:10,padding:4,alignSelf:"flex-start"}}>{[{k:"details",l:"Phase Details"},{k:"logs",l:"Pipeline Log"}].map(t=>(<button key={t.k} onClick={()=>setTab(t.k)} style={{padding:"8px 20px",borderRadius:8,border:"none",fontSize:13,fontWeight:700,cursor:"pointer",background:tab===t.k?C.white:"transparent",color:tab===t.k?C.textPrimary:C.textMuted,boxShadow:tab===t.k?"0 1px 3px rgba(0,0,0,0.08)":"none"}}>{t.l}</button>))}</div>
        <div style={{animation:"fadeIn 0.2s ease"}}>{tab==="details"&&<PhaseDetail phase={po} result={rs}/>}{tab==="logs"&&<LogTerminal logs={logs}/>}</div>
      </>)}
    </div></div></>}
  </div>);
}
