version: 2.0.0
last_updated: '2026-03-29T18:06:09.786062'
updated_by: dashboard-ui
environment_name: PERF
lab_environment: PERF
release_code: current
application_key: gddn-messaging
application_display_name: GDDN Messaging
api_variant: core
applications:
- app_name: GDDN Messaging
  app_description: GDDN Data Transformation & Solace Message Queuing
  tags:
  - middleware
  - gddn
  - solace
  - critical
  config_fields:
  - field_name: SOLACE_HOST
    expected_perf_value: solace-perf.internal.att.com
    inspection_tool: solace_semp
    description: Solace broker host
    known_qc_values:
    - solace-qc3.internal.att.com
    remediation_level: suggest_fix
    remediation_command: null
  - field_name: SOLACE_VPN
    expected_perf_value: perf-vpn
    inspection_tool: solace_semp
    description: Solace message VPN
    known_qc_values:
    - qc3-vpn
    remediation_level: suggest_fix
    remediation_command: null
  - field_name: SOLACE_QUEUE_MANAGER
    expected_perf_value: PERFQM01
    inspection_tool: solace_semp
    description: Solace queue manager
    known_qc_values:
    - QC3QM01
    - QC2QM01
    remediation_level: suggest_fix
    remediation_command: null
  - field_name: BASE_ENDPOINT_URL
    expected_perf_value: https://gddn-perf.att.com
    inspection_tool: http_probe
    description: Primary endpoint URL for this application in PERF
    known_qc_values: []
    remediation_level: suggest_fix
    remediation_command: null
